dataset_name: anet
train_split: ['training']
val_split: ['validation']
dataset: {
  json_file: ./data/anet_1.3/annotations/anet1.3_tsp_filtered.json,
  feat_folder: /mnt/petrelfs/liuyi/data_feature/anet_tsp,
  file_prefix: v_,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 1280,
  #512 +768  +1024=1536  +1280=1792  1024
  feat_stride: 16,
  num_frames: 16,
  default_fps: 15,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 768,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 1.0,
  n_mha_win_size: [25, 25, 25, 25, 25, -1],
  # shrink the model for reduced input feature channels
  n_head: 4,
  embd_dim: 256,
  fpn_dim: 256,
  head_dim: 256,
  use_abs_pe: True,
}
# learning_rate: 0.001
opt: {
  learning_rate: 0.001,
  epochs: 10,
  weight_decay: 0.05,
}
loader: {
  batch_size: 8,
}
train_cfg: {
  init_loss_norm: 400,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  label_smoothing: 0.1,
}

# similar to THUMOS
test_cfg: {
  voting_thresh: 0.9,
  pre_nms_topk: 2000,
  # max of 100 predictions per video
  max_seg_num: 100,
  min_score: 0.001,
  # score fusion
  multiclass_nms: False,
  nms_sigma : 0.75,
  # ext_score_file: ./data/anet_1.3/annotations/cuhk_val_simp_share.json,
  ext_score_file: ./data/anet_1.3/annotations/new_3ensemble_uniformerv2_large_only_global_anet_16x10x3.json
  duration_thresh: 0.1,
}
output_folder: ./ckpt_anet/
