BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
TRAINER_NAME: ss
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/tensorboard_dirs/cma_ss
CHECKPOINT_FOLDER: data/checkpoints/cma_ss
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_ss

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

#RL:
#  POLICY:
#    OBS_TRANSFORMS:
#      ENABLED_TRANSFORMS: [Resize]

IL:
  epochs: 50
  batch_size: 8
  schedule_ratio: 0.75
  decay_time: 10

  max_traj_len: 130

MODEL:
  policy_name: CMAPolicyO

  INSTRUCTION_ENCODER:
    bidirectional: True
