BASE_TASK_CONFIG_PATH: habitat_extensions/config/r2r_vlnce.yaml
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
TORCH_GPU_IDS: [0]
TRAINER_NAME: HAMT
GPU_NUMBERS: 1
NUM_ENVIRONMENTS: 1
TENSORBOARD_DIR: data/logs/tensorboard_dirs/
CHECKPOINT_FOLDER: data/logs/checkpoints/
CEPH_URL: s3://checkpoints/
EVAL_CKPT_PATH_DIR: data/logs/checkpoints/
RESULTS_DIR: data/logs/eval_results/
VIDEO_DIR: data/logs/video/
CEPH_IO: False

INFERENCE:
  SPLIT: test
  USE_CKPT_CONFIG: False
  SAMPLE: False
  CKPT_PATH: '' # REPLACE THIS
  PREDICTIONS_FILE: ''
  FORMAT: r2r

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1
  CKPT_PATH_DIR: ''
  ANG30: False

IL:
  iters: 10000
  log_every: 100
  lr: 2e-5
  batch_size: 1 # equal to NUM_ENVIRONMENTS
  ml_weight: 1.0
  feedback: sample
  resume: True
  style_aug: False

  sample_ratio: 0.75
  decay_interval: 2000
  
  max_traj_len: 25
  max_text_len: 200
  waypoint_aug: True
  progress_monitor: False

MODEL:
  task_type: r2r

  policy_name: PolicyViewSelectionHAMT
  NUM_ANGLES: 12
  pretrained_path: pretrained/HAMT/vitbase-6tasks-pretrain/model_step_130000.pt
  fix_lang_embedding: True
  fix_hist_embedding: True
  fix_obs_embedding: False
  
  spatial_output: False
  RGB_ENCODER:
    backbone_type: VideoIntern-Base
    output_size: 768
  DEPTH_ENCODER:
    output_size: 256    
  VISUAL_DIM:
    vis_hidden: 768
    directional: 128
  INSTRUCTION_ENCODER:
    bidirectional: True

