VIDEO_PROMPTS = [
    "Quickly describe the main elements of the following video.", 
    "Provide a brief overview of the video's content.", 
    "Offer a succinct synopsis of the clip presented.", 
    "Summarize the main actions in the given video.", 
    "Explain the key highlights of the subsequent footage.", 
    "Share a concise summary of this video clip.", 
    "Present a compact outline of the video's focus.", 
    "Relay a brief, clear account of the scene shown.", 
    "Detail the primary aspects of the video below.", 
    "Write a short, informative overview of the following footage.", 
    "Create a compact narrative representing the video provided.", 
    "Outline the main events of the video in a few words.", 
    "Give a brief rundown of the video's content.", 
    "Concisely explain the main points of the clip.", 
    "Describe the crucial moments in the video succinctly.", 
    "Identify the key components of the given footage.", 
    "Provide an abridged description of the video's subject.", 
    "Offer a terse explanation of the video presented.", 
    "Capture the essence of the clip in a few words.", 
    "Explain briefly the central theme of the video.", 
    "Share a condensed interpretation of the scene shown.", 
    "Describe the core message of the video quickly.", 
    "Give a pithy account of the following footage.", 
    "Shorten the video's story into a few words.", 
    "Interpret the video's main idea concisely.", 
    "Illustrate the video's plot in a brief statement.", 
    "Provide a crisp summary of the video's action.", 
    "Offer a fast-paced description of the clip.", 
    "Highlight the most significant parts of the video.", 
    "Identify the main elements in a short, clear manner.", 
    "Outline the video's content with brevity and clarity.", 
    "Recount the key events of the scene concisely.", 
    "Describe the video's atmosphere in a brief statement.", 
    "Share a snapshot of the video's subject matter.", 
    "Present the major aspects of the footage succinctly.", 
    "Relay a focused summary of the video's intent.", 
    "Craft a concise depiction of the clip's purpose.", 
    "Narrate the essential action in the video briefly.", 
    "Enumerate the highlights of the provided footage.", 
    "Capture the video's mood in a few words.", 
    "Sum up the core message of the clip concisely.", 
    "Touch on the crucial elements of the video.", 
    "Offer a compressed explanation of the scene.", 
    "Explain the video's storyline in a nutshell.", 
    "Convey a streamlined understanding of the footage.", 
    "Distill the essence of the video in a short description.", 
    "Provide a minimalist summary of the given clip.", 
    "Characterize the primary focus of the video quickly.", 
    "Reveal the central theme of the clip tersely.", 
    "Give a laconic account of the actions presented.", 
    "Paint a picture of the video using minimal words.", 
    "Report the video's main message with brevity.", 
    "Provide an economical overview of the clip's content.", 
    "Summarize the focal points of the scene shown.", 
    "Express the video's purpose in a compact manner.", 
    "Discuss the essentials of this video concisely.", 
    "Streamline the key events of the clip into a brief summary.", 
    "Share a simplified interpretation of the video's subject.", 
    "Clarify the main message of the footage with few words.", 
    "Illustrate the video's concept in a concise statement.", 
    "Offer an efficient summary of the clip's theme.", 
    "Present the video's content in a straightforward manner.", 
    "Narrate the primary aspects of the scene tersely.", 
    "Identify the critical points of the video concisely.", 
    "Outline the most important parts of the footage.", 
    "Capture the gist of the clip in a short explanation.", 
    "Describe the video's narrative in a precise manner.", 
    "Provide a trimmed-down version of the video's story.", 
    "Report on the key moments of the clip succinctly.", 
    "Highlight the standout features of the video.", 
    "Express the central idea of the footage briefly.", 
    "Recount the crucial events in the video with few words.", 
    "Share a brief impression of the video's atmosphere.", 
    "Offer a synoptic view of the clip's main elements.", 
    "Present a concise account of the video's highlights.", 
    "Enumerate the most significant scenes from the clip.", 
    "Sum up the essential components of the footage.", 
    "Create a compact overview of the video's main actions.", 
    "Expound on the key aspects of the clip in a minimalist style.", 
    "Give a condensed portrayal of the video's core.", 
    "Reveal the heart of the video with brevity and clarity.", 
    "Explain the key takeaways from the scene provided.", 
    "Describe the video's main focus in a direct manner.", 
    "Summarize the essence of the clip quickly and concisely.", 
    "Provide a snapshot of the video's most important moments.", 
    "Share your impressions of the footage in a few words.", 
    "Offer a quick rundown of the video's main points.", 
    "Present a short and clear breakdown of the clip's content.", 
    "Relay a straightforward summary of the video's narrative.", 
    "Distill the primary themes of the footage into a concise description., "
    "Explain the video's central premise with minimal words.", 
    "Illustrate the key ideas presented in the clip concisely.", 
    "Provide a terse overview of the video's main message.", 
    "Describe the following video in a condensed way.", 
    "Sum up the action and purpose of the clip succinctly.", 
    "Give a brief but comprehensive account of the video's content.", 
    "Share a concise and diverse interpretation of the footage.", 
    "Write a compact summary of the video's crucial aspects.", 
    "Create a pithy narrative representing the scene presented.", 
    "Provide an abridged and focused explanation of the video.", 
]

IMAGE_PROMPTS = [
    "Portray the contents of this image in a few words.", 
    "Characterize the given image briefly.", 
    "Depict the essence of the picture with brevity.", 
    "Articulate a short outline of the visual presented.", 
    "Offer a truncated summary of the following image.", 
    "Supply a condensed description of the subsequent photo.", 
    "Deliver a crisp overview of the displayed image.", 
    "Communicate the main aspects of this picture briefly.", 
    "Enumerate key elements of the image concisely.", 
    "Furnish a terse snapshot of the visual content.", 
    "Recount an abridged version of the photograph's features.", 
    "Provide a pithy synopsis of the scene depicted.", 
    "Convey a laconic account of the photographic subject matter.", 
    "Sketch the visual narrative of the image in a few words.", 
    "Verbally paint a minimalist representation of the picture.", 
    "Distill the essence of the following image in one sentence.", 
    "Craft a succinct story for the provided photograph.", 
    "Narrate a brief tableau of the image on display.", 
    "Share a compact analysis of the picture's composition.", 
    "Generate a truncated rendition of the image's narrative.", 
    "Delineate the core elements of the photo in a nutshell.", 
    "Unveil a concise depiction of the visual scenario.", 
    "Exhibit a shortened impression of the framed image.", 
    "Disclose a summarized perspective of the image portrayed.", 
    "Impart a brief understanding of the focal points in the photo.", 
    "Draft a brief but vivid explanation of the picture.", 
    "Outline the primary subjects in the photograph.", 
    "Reveal a concise portrayal of the image at hand.", 
    "Narrate the image without being verbose.", 
    "Define the main theme of the picture succinctly.", 
    "Analyze the photo briefly, focusing on key parts.", 
    "Explain what's happening in the image with brevity.", 
    "Decipher the visual clues and share a brief insight.", 
    "Describe the most striking aspects of this image.", 
    "Offer a clipped interpretation of the photograph.", 
    "Produce a short but meaningful summary of the picture.", 
    "Concoct a shortened depiction of the scene.", 
    "Report the main idea of the image in few words.", 
    "Express the image's atmosphere briefly.", 
    "State the essential components of the given photo.", 
    "Reproduce a concise understanding of the image's story.", 
    "Illustrate the image concisely yet vividly.", 
    "Condense the essence of the photograph into a sentence.", 
    "Share a reduced version of the image's message.", 
    "Elucidate the key points of the picture with economy.", 
    "Give me the gist of the image in one sentence.", 
    "Capture the mood of the photo in a few words.", 
    "Briefly evaluate the visual elements in the picture.", 
    "Describe the image with a minimalist approach.", 
    "Communicate the core ideas of the photograph concisely.", 
    "Identify central themes in this image and summarize.", 
    "Provide a brief annotation for the image displayed.", 
    "Interpret the following image without over-explaining.", 
    "Whittle down the description to the vital elements.", 
    "Break down the visual content into its bare essentials.", 
    "Convey a tight overview of the photo's subject matter.", 
    "Present a minimized account of the image's content.", 
    "Exhibit a compressed version of the image's elements.", 
    "Streamline the explanation of the photo into key points.", 
    "Bring out the essence of the image in a concise manner.", 
    "Offer a clipped observation of the scene.", 
    "Distill the visual details into a brief summary.", 
    "Write a short, clear description of the picture's intent.", 
    "Share a succinct understanding of the image's context.", 
    "Give me a precise breakdown of the photograph.", 
    "State a concise interpretation of the featured image.", 
    "Evoke the spirit of the image in as few words as possible.", 
    "Focus on key aspects while describing the picture.", 
    "Illustrate the image with a minimalist touch.", 
    "Express your thoughts on the image in a few words.", 
    "Grasp the gist of the photograph and summarize.", 
    "Paraphrase the story of the image concisely.", 
    "Capture the image's impact with a short statement.", 
    "Write an abridged reflection on the photo's contents.", 
    "Convey the main idea in a nutshell.", 
    "Emphasize the central theme in few words.", 
    "Unravel the essence of the image with brevity.", 
    "Divulge the story behind the photo briefly.", 
    "Cut down the description to vital features only.", 
    "Translate the image's narrative into one sentence.", 
    "Curtail the details and focus on the core message.", 
    "Provide a summarized tour of the image's composition.", 
    "Highlight the main components of the picture.", 
    "Reveal the essence of the image with a short statement.", 
    "Parse the image into its most important aspects.", 
    "Compress the image's content into a single sentence.", 
    "Present a brief snapshot of the visual scene.", 
    "Weave a concise narrative around the image.", 
    "Communicate the photo's message with precision.", 
    "Explain the image using only its most essential features.", 
    "Illustrate the key points of the photo in few words.", 
    "Offer a short, focused account of the image's content.", 
    "Share a brief overview of the picture's composition.", 
    "Deliver an abbreviated version of the photo's story.", 
    "Craft a short but impactful description of the image.", 
    "Report on the main elements of the photo concisely.", 
    "Demonstrate a clear understanding of the image with brevity.", 
    "Unfold the essence of the photograph quickly.", 
    "Provide a cursory assessment of the picture's focal points.", 
    "Explain the theme of the image briefly and distinctly.", 
]